conda/gds_dev_env.yml
pyTigerGraph/gds/dataloaders.py
pyTigerGraph/gds/gds.py
pyTigerGraph/gds/gsql/dataloaders/edge_nei_loader.gsql
pyTigerGraph/gds/gsql/dataloaders/neighbor_loader.gsql
pyTigerGraph/gds/gsql/splitters/random_edge_split.gsql
pyTigerGraph/gds/gsql/splitters/random_vertex_split.gsql
pyTigerGraph/gds/splitters.py
tests/test_gds_EdgeNeighborLoader.py
tests/test_gds_splitters.py

Code Changes:
1. Allow filter_by given vertex or edge types for neighbor loader and edge neighbor loader
2. Allow users to specify vertex or edge types for splitters
Testing:
* New unit tests included.
* All unit tests passed

Follow up updates for heterogeneous graphs

---

pyTigerGraph/gds/dataloaders.py
pyTigerGraph/gds/gds.py
pyTigerGraph/gds/gsql/dataloaders/edge_loader.gsql
pyTigerGraph/gds/gsql/dataloaders/edge_nei_loader.gsql
pyTigerGraph/gds/gsql/dataloaders/graph_loader.gsql
pyTigerGraph/gds/gsql/dataloaders/neighbor_loader.gsql
pyTigerGraph/gds/gsql/dataloaders/vertex_loader.gsql
tests/test_gds_BaseLoader.py
tests/test_gds_EdgeLoader.py
tests/test_gds_EdgeNeighborLoader.py
tests/test_gds_GraphLoader.py
tests/test_gds_NeighborLoader.py
tests/test_gds_VertexLoader.py

Code change:
* Add sasl_plaintext and sasl_ssl authentication for kafka
Testing:
* Unit tests added
* Unit tests passed

Kafka auth

---

pyTigerGraph/gds/dataloaders.py
pyTigerGraph/pyTigerGraphGSQL.py
tests/test_gds_BaseLoader.py

Code change
* Fix issue https://graphsql.atlassian.net/browse/GML-634: bool label is always True.
Testing 
* Unit tests added and passed

fix: convert bool attr to int and then to bool

---

pyTigerGraph/pyTigerGraphAuth.py
tests/pyTigerGraphUnitTest.py
tests/test_pyTigerGraphAuth.py

Associated with: https://dev.tigergraph.com/forum/t/pytigergraph-refreshtoken-method-error/2610

fix(refresh and delete token): update to be compatible with v3.5+ DB

---

pyTigerGraph/gds/dataloaders.py
tests/test_gds_BaseLoader.py

Code change:
* Add heterograph for DGL output
Testing:
* Unit tests added and passed

feat: add DGL heterograph

---

pyTigerGraph/gds/dataloaders.py
pyTigerGraph/gds/gds.py
pyTigerGraph/gds/metrics.py
pyTigerGraph/gds/utilities.py

This big and mixed PR includes many fixes/enhancements due to the test run of KDD tutorial, which includes 
1. Make sure topic is fully created before using it.
2. Make sure topic creation, consumer, producer are called in order.
3. Make sure queries are enabled before calling them.
Testing
1. Manually tested at KDD
2. Corresponding unit tests are updated

All updates from KDD test

---

pyTigerGraph/__init__.py
pyTigerGraph/gds/dataloaders.py
pyTigerGraph/gds/gds.py

Support for homogeneous graphs and Spektral. Tested with `EdgeNeighborLoader`, `GraphLoader`, and `NeighborLoader`.

feat: homogeneous Spektral support

---

pyTigerGraph/gds/dataloaders.py
tests/test_gds_BaseLoader.py
tests/test_gds_GraphLoader.py

Code change:
* Allow data loaders to pull list<string> attributes in v_extra_feat and e_extra_feat.
* Add a stringify UDF for all string converting functions.
* Fix kafka not initialized error. 
* Change some tests to use the new testing environment.
Testing:
* Unit tests added and passed

Support list<string> attributes and minor fixes

---

pyTigerGraph/pyTigerGraph.py
pyTigerGraph/pyTigerGraphBase.py
pyTigerGraph/pyTigerGraphEdge.py
pyTigerGraph/pyTigerGraphLoading.py
pyTigerGraph/pyTigerGraphVertex.py

Added depreciation handling (plus a little code cleaning/formatting).

Added depreciation handling

---

.gitignore
pyTigerGraph/datasets.py
pyTigerGraph/pyTigerGraph.py
pyTigerGraph/pyTigerGraphDataset.py
tests/test_datasets.py

Code change:
* Add a one-liner function to ingest our example data to database
* Design doc: https://graphsql.atlassian.net/wiki/spaces/GDS/pages/2907963473/Datasets+Function
Testing
* Unit test included

feat: refactor and add Datasets class

---

.gitignore
pyTigerGraph/pyTigerGraphQuery.py
tests/README.md
tests/pyTigerGraphUnitTest.py
tests/test_pyTigerGraphAuth.py
tests/test_pyTigerGraphBase.py
tests/test_pyTigerGraphEdge.py
tests/test_pyTigerGraphGSQL.py
tests/test_pyTigerGraphPath.py
tests/test_pyTigerGraphQuery.py
tests/test_pyTigerGraphSchema.py
tests/test_pyTigerGraphUDT.py
tests/test_pyTigerGraphUtils.py
tests/test_pyTigerGraphVertex.py
tests/testserver.cfg

I got some error running the unit tests on 3.7.0. And not sure if those issues are db version dependent.

fix: error in Auth

---

pyTigerGraph/gds/featurizer.py

fix(featurizer): fix urls for degree centrality

---

pyTigerGraph/pyTigerGraph.py
pyTigerGraph/pyTigerGraphDataset.py
pyTigerGraph/visualization.py

1. Add drawSchema with ipycytoscape
2. Fix auth error in Dataset Ingestion when DB token auth is on

Visualize schema

---

pyTigerGraph/pyTigerGraphDataset.py

In dataset ingestion, set graph name if graph already exists in the database.

Gml 1006 fix ingestion

---

pyTigerGraph/datasets.py
pyTigerGraph/gds/metrics.py
pyTigerGraph/pyTigerGraphDataset.py
tests/test_gds_featurizer.py

1. Improve data ingestion print out
2. Skip downloading if dataset exists on disk
3. Fix metrics issue
4. Fix unit test issue in featurizer

GML-1035: improve ingestion print out

---

pyTigerGraph/gds/featurizer.py
tests/test_gds_featurizer.py

Code change
* Allow user to get parameters for any built-in algo using getParams function
* Validate input parameters to runAlgorithm

GML-1049: get and check parameters for query

---

pyTigerGraph/datasets.py
setup.py
tests/test_pyTigerGraphQuery.py

Code change:
* Add tqdm as a dependency for the gds package
* Import tqdm when needed in datasets.
* If tqdm is not installed, give a warning and proceed without it.

Fix tqdm dependency in datasets

---

README.md

Added three badges for total, monthly, and weekly downloads

🥳 Add statistics badges to readme

---

pyTigerGraph/gds/__init__.py
pyTigerGraph/gds/metrics.py
pyTigerGraph/gds/models/GraphSAGE.py
pyTigerGraph/gds/models/__init__.py
pyTigerGraph/gds/models/base_model.py
pyTigerGraph/gds/trainer.py
tests/test_gds_GraphSAGE.py
tests/test_gds_Trainer.py

To-dos in future PRs:
- Finalize Metrics (add link prediction @k metrics)
- Write NodePiece Built-ins
- Further expand tests
- `.fit()` method in built-in models
- `.predict()` method in trainer and built-in models
- Refactor metrics collection to happen in callbacks
- Update metrics to include multi-class precision/recall, hits@k, recall@k, etc.
- Make heterogeneous graph metadata available as dataloader class attribute
- TQDM support in callbacks
- `filter_by` in dataloaders factory function to accept a list such that it will return multiple dataloaders, one for each filter condition
- clean up logging levels in core functions so that training logs only contain metrics

Gml 1147 training loop

---

pyTigerGraph/pyTigerGraphVertex.py
tests/test_pyTigerGraphVertex.py

Same as https://github.com/tigergraph/pyTigerGraph/pull/131 but change base branch to v1.3

GML-1241: fix timeout or out-of-memory issue with getVertexCount

---

pyTigerGraph/gds/models/base_model.py
pyTigerGraph/gds/trainer.py
tests/test_gds_Trainer.py

Do not run tests until 1.4 rc ready. Rebase with master before running tests.

GML-1210: Add predict() to trainer and models

---

pyTigerGraph/pyTigerGraphUtils.py
tests/test_pyTigerGraphUtils.py

Do not run tests until v1.4 rc ready, and rebase with master before running tests/merge.

GML-1247: system util endpoints

---

pyTigerGraph/gds/dataloaders.py
pyTigerGraph/gds/gsql/dataloaders/nodepiece_loader.gsql

Batch heap message passing, fix error when selecting batches when not using filter

GML-1262: Improve NodePiece Scalability

---

pyTigerGraph/gds/__init__.py
pyTigerGraph/gds/transforms/pyg_transforms.py
tests/test_gds_transforms.py

Will wait to merge/run tests after 1.4 UDF changes are complete. Rebase with master will be necessary before testing.

Gml 1201 temporal callback transform

---

pyTigerGraph/gds/dataloaders.py
tests/test_gds_NeighborLoader.py

@billshitg how should we test this? Is the way I went about deleting the kafka topic the best way?

feat(dataloaders): add stop() function

---

pyTigerGraph/pyTigerGraphGSQL.py

Temporary solution for handling error in GSQL commands for BigQuery uses, including, schema creation, data source creation, and loading job creating and running.

GML-1273: Error handling for BigQuery uses

---

README.md

Fixed download tickers/badges.

---

pyTigerGraph/pyTigerGraphSchema.py

See https://dev.tigergraph.com/forum/t/potential-bug-report-for-3-9-3-map-attribute-problem/3635/3

Fxied typos in _upsertAttrs()

---

pyTigerGraph/pyTigerGraphEdge.py

fix(upsertEdge): fix string formatting for json.

---

pyTigerGraph/pyTigerGraphGSQL.py

Checks just if "LOAD SUCCESSFUL" exists in response string which is consistent with older and newer versions of TigerGraph.

227 run loading job raises exception on newer versions

---

pyTigerGraph/__init__.py
pyTigerGraph/pyTigerGraphAuth.py
pyTigerGraph/pyTigerGraphBase.py
tests/test_jwtAuth.py
tests/test_pyTigerGraphAuth.py

fix getToken

---

pyTigerGraph/common/auth.py

https://github.com/tigergraph/pyTigerGraph/issues/273

fix: fix issue #273
